// Copies only the Noto Serif SC font slices that cover the Chinese characters used in the app,
// and writes src/fonts.css. Re-run after adding lessons:  node scripts/subset-fonts.mjs
import fs from 'node:fs';
import path from 'node:path';

const WEIGHTS = [500, 700];
const pkg = 'node_modules/@fontsource/noto-serif-sc';
const outDir = 'src/assets/fonts';

// 1. Collect every CJK character in the source.
const used = new Set('声学好你我他她是不的了们吗呢吧很都也'.split(''));
const walk = (d) => {
  for (const f of fs.readdirSync(d, { withFileTypes: true })) {
    const p = path.join(d, f.name);
    if (f.isDirectory()) walk(p);
    else if (/\.(ts|tsx)$/.test(f.name)) for (const ch of fs.readFileSync(p, 'utf8')) if (/[㐀-鿿]/.test(ch)) used.add(ch);
  }
};
walk('src');

// 2. Keep only the slices whose unicode-range covers a used character.
const inRange = (ranges, cp) =>
  ranges.some(([a, b]) => cp >= a && cp <= b);
const parseRanges = (s) =>
  s.split(',').map((r) => r.trim().replace(/^U\+/i, '')).map((r) => {
    const [a, b] = r.split('-');
    return [parseInt(a, 16), parseInt(b ?? a, 16)];
  });

fs.rmSync(outDir, { recursive: true, force: true });
fs.mkdirSync(outDir, { recursive: true });
let css = '/* Generated by scripts/subset-fonts.mjs. Do not edit. */\n';
let kept = 0;
for (const weight of WEIGHTS) {
  const src = fs.readFileSync(`${pkg}/${weight}.css`, 'utf8');
  for (const block of src.match(/@font-face\s*{[^}]*}/g) ?? []) {
    const url = block.match(/url\(([^)]*?\.woff2)\)/)?.[1]?.replace(/['"]/g, '');
    const range = block.match(/unicode-range:\s*([^;]+);/)?.[1];
    if (!url || !range) continue;
    const ranges = parseRanges(range);
    if (![...used].some((ch) => inRange(ranges, ch.codePointAt(0)))) continue;
    const file = path.basename(url);
    fs.copyFileSync(path.join(pkg, url.replace(/^\.\//, '')), path.join(outDir, file));
    css += `@font-face{font-family:'Noto Serif SC';font-style:normal;font-display:swap;font-weight:${weight};src:url(./assets/fonts/${file}) format('woff2');unicode-range:${range};}\n`;
    kept++;
  }
}
fs.writeFileSync('src/fonts.css', css);
const size = fs.readdirSync(outDir).reduce((n, f) => n + fs.statSync(path.join(outDir, f)).size, 0);
console.log(`${used.size} characters -> ${kept} font slices, ${(size / 1e6).toFixed(1)} MB`);
